name: Linting of OpenAPI documents on Pull Requests

on:
  pull_request:
    branches:
      - master
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  json-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - run: npm install -g jsonlint

      - name: Lint JSON schema example responses
        run: |
          shopt -s globstar nullglob
          files=$(find src/main/resources/openapi/schema -name "*.json" ! -name "*.example.json")
          if [ -z "$files" ]; then
            echo "✅ No example JSON files to lint."
          else
            for file in $files; do
              echo "Linting $file"
              jsonlint -q "$file" || exit 1
            done
          fi

  json-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - run: npm install ajv ajv-formats ajv-keywords

      - name: Validate JSON schema responses
        run: |
          curl -sSfL https://raw.githubusercontent.com/hmcts/api-cp-code-style/refs/heads/master/lint/scripts/ajv-validate.js -o ajv-validate.js

          for schemaFile in $(find src/main/resources/openapi -name "*.json" ! -name "*.example.json"); do
            datafile="${schemaFile/.json/.example.json}"
            echo "datafile=$datafile"

            if [ -f "$datafile" ]; then
              echo "Validating $datafile against schema $schemaFile"
              node ajv-validate.js "$schemaFile" "$datafile" || exit 1
            else
              echo "⚠️ Skipping: no example file found for $schemaFile"
            fi
          done

  spectral-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - run: npm install -g @stoplight/spectral-cli

      - name: Run Spectral on API specs
        run: |
          spectral lint "src/main/resources/openapi/*.{yml,yaml}" || exit 1
