name: Validate OpenAPI Definition

on:
  pull_request:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        id: cache-pip
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
          cache-dependency-path: |
            ${{ github.workspace }}/.github/scripts/requirements.txt

      - name: Install dependencies
        run: |
          if [ "${{ steps.cache-pip.outputs.cache-hit }}" = "true" ]; then
            echo "Cache hit - verifying dependencies..."
            pip install --root-user-action=ignore -r $GITHUB_WORKSPACE/.github/scripts/requirements.txt --upgrade --upgrade-strategy eager
          else
            echo "Cache miss - installing dependencies..."
            pip install --root-user-action=ignore -r $GITHUB_WORKSPACE/.github/scripts/requirements.txt
          fi

      - name: Validate OpenAPI definitions
        env:
          OAPI_SCHEMA_URL: "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/refs/tags/3.1.1/schemas/v3.0/schema.yaml"
        run: |
          echo "Validating OpenAPI definitions..."
          
          # Run validation using the existing script
          echo "Running OpenAPI validation script..."
          python $GITHUB_WORKSPACE/.github/scripts/validate_openapi.py $GITHUB_WORKSPACE/openapi || exit 1
          echo "Validation script completed."

          # Check for validation results
          VALIDATION_EXIT_CODE=$?
          echo "Validation exit code: $VALIDATION_EXIT_CODE"

          if [ $VALIDATION_EXIT_CODE -ne 0 ]; then
            echo "OpenAPI validation failed with $VALIDATION_EXIT_CODE errors."
            exit 1
          else
            echo "All OpenAPI definitions are valid."
          fi
